In [1]:
import ast

import pandas as pd
import sqlite3

In [2]:
df = pd.read_csv('blackboard.csv')
df.head()

,instance_id,issue_link,problem_statement,issue_category,image_assets,image_category_1,image_category_2,name
0,bpmn-io__bpmn-js-2024,https://github.com/bpmn-io/bpmn-js/issues/57,Correctly render pool / lane labels in vertica...,[1.1 Incomplete Data Processing],['https://cloud.githubusercontent.com/assets/5...,Diagram,Program Output,daniel
1,bpmn-io__bpmn-js-1200,https://github.com/bpmn-io/bpmn-js/issues/1199,"""Timer Intermediate Catch Event"" removes ""cond...",[2.1 Incorrect Data Processing],['https://user-images.githubusercontent.com/80...,Code Snippet Screenshot,Steps and Processes,daniel
2,bpmn-io__bpmn-js-1610,https://github.com/bpmn-io/bpmn-js/issues/1609,Direct editing in sub-process plane stays open...,[1.3 Error Handling],['https://user-images.githubusercontent.com/58...,Diagram,Program Output,daniel
3,bpmn-io__bpmn-js-1578,https://github.com/bpmn-io/bpmn-js/issues/1555,Error when copy Pool\n__Describe the Bug__\n\n...,[2.1 Incorrect Data Processing],['https://user-images.githubusercontent.com/15...,Web Interface (UI/UX Element),Run Time Error,daniel
4,bpmn-io__bpmn-js-1584,https://github.com/bpmn-io/bpmn-js/issues/1508,Inconsistent redo behaviour when recreating th...,[1.2.3 Missing Null Check],['https://user-images.githubusercontent.com/15...,Web Interface (UI/UX Element),Run Time Error,daniel

In [3]:
mask = df['issue_link'].str.contains(' ') | df['issue_link'].str.contains('\n') | df['issue_link'].str.contains(',')
df_filtered = df[mask]
df_filtered.head()

,instance_id,issue_link,problem_statement,issue_category,image_assets,image_category_1,image_category_2,name
85,openlayers__openlayers-12695,https://github.com/openlayers/openlayers/issue...,KML Symbol Alignment/Placement/Size\nI believe...,[2.4 Incorrect output],['https://user-images.githubusercontent.com/43...,Map/Geospatial Visualization,"Program Output, Desired Output",yaseen
108,openlayers__openlayers-15466,https://github.com/openlayers/openlayers/issue...,Fix image+label combinations when declutterMod...,[4 Perfective maintenance],[https://raw.githubusercontent.com/openlayers/...,Diagram,Desired Output,yaseen
145,openlayers__openlayers-12695,https://github.com/openlayers/openlayers/issue...,KML Symbol Alignment/Placement/Size\nI believe...,[2.4 Incorrect output],['https://user-images.githubusercontent.com/43...,Map/Geospatial Visualization,"Program Output, Desired Output",tan
168,openlayers__openlayers-15466,https://github.com/openlayers/openlayers/issue...,Fix image+label combinations when declutterMod...,[4 Perfective maintenance],[https://raw.githubusercontent.com/openlayers/...,Diagram,Desired Output,tan
243,openlayers__openlayers-13669,https://github.com/openlayers/openlayers/issue...,GeoTiff: Issue with alpha band and no-data val...,2.1 Incorrect data processing,[https://raw.githubusercontent.com/openlayers/...,Map/Geospatial Visualization,Desired Output,daniel

In [4]:
print(df['issue_category'].unique().tolist())
[
    '[1.1 Incomplete Data Processing]',
    '[2.1 Incorrect Data Processing]',
    '[1.3 Error Handling]',
    '[1.2.3 Missing Null Check]',
    '[2.2 Incorrect Input Validation]',
    '[4 Perfective Maintenance]',
    '2.4 Incorrect output',
    '2.5 Incorrect configuration processing',
    '2.1 Incorrect data processing',
    '1.4 Incomplete configuration processing',
    '1.1 Incomplete data processing',
    '[2.2.2 Incorrect Handling of Special Characters]',
    '[2.4.1 Incorrect Output Message]',
    '[1.2.3 Missing null check]',
    '[2.1 Incorrect data processing]',
    '[1.2 Incomplete input validation]',
    '[2.4 Incorrect output]',
    '[1.4 Incomplete Configuration Processing]',
    '[1.1 Incomplete data processing]',
    '[2.5 Incorrect configuration processing]',
    '[2.1.2 Incorrect initialization]',
    '[4 Perfective maintenance]',
    '[2.7 Performance]',
    '[1.4 Incomplete configuration processing]',
    '2.2 Incorrect input validation',
    '[2.1.2 Incorrect Initialization]',
    '[3.3.1 Missing Initialization]',
    '[1.2 Missing Input Validation]',
    '[1.5 Incomplete Output Message]',
    '[1.2.1 Missing Type Check]',
    '4 Perfective maintenance',
    '2.7 Performance',
    '2.2.2 Incorrect handling of special characters',
    '1.2.5 Missing handling of special characters',
    '2.6 Incorrect handling of regex expressions',
    '1 Incomplete feature implementation',
    '2 Incorrect feature implementation',
    '1.3 Error handling',
    '1.2.3 Missing null check',
    '4 Perfective Maintenance',
]

['[1.1 Incomplete Data Processing]', '[2.1 Incorrect Data Processing]', '[1.3 Error Handling]', '[1.2.3 Missing Null Check]', '[2.2 Incorrect Input Validation]', '[4 Perfective Maintenance]', '2.4 Incorrect output', '2.5 Incorrect configuration processing', '2.1 Incorrect data processing', '1.4 Incomplete configuration processing', '1.1 Incomplete data processing', '[2.2.2 Incorrect Handling of Special Characters]', '[2.4.1 Incorrect Output Message]', '[1.2.3 Missing null check]', '[2.1 Incorrect data processing]', '[1.2 Incomplete input validation]', '[2.4 Incorrect output]', '[1.4 Incomplete Configuration Processing]', '[1.1 Incomplete data processing]', '[2.5 Incorrect configuration processing]', '[2.1.2 Incorrect initialization]', '[4 Perfective maintenance]', '[2.7 Performance]', '[1.4 Incomplete configuration processing]', '2.2 Incorrect input validation', '[2.1.2 Incorrect Initialization]', '[3.3.1 Missing Initialization]', '[1.2 Missing Input Validation]', '[1.5 Incomplete Output Message]', '[1.2.1 Missing Type Check]', '4 Perfective maintenance', '2.7 Performance', '2.2.2 Incorrect handling of special characters', '1.2.5 Missing handling of special characters', '2.6 Incorrect handling of regex expressions', '1 Incomplete feature implementation', '2 Incorrect feature implementation', '1.3 Error handling', '1.2.3 Missing null check', '4 Perfective Maintenance']

['[1.1 Incomplete Data Processing]',
 '[2.1 Incorrect Data Processing]',
 '[1.3 Error Handling]',
 '[1.2.3 Missing Null Check]',
 '[2.2 Incorrect Input Validation]',
 '[4 Perfective Maintenance]',
 '2.4 Incorrect output',
 '2.5 Incorrect configuration processing',
 '2.1 Incorrect data processing',
 '1.4 Incomplete configuration processing',
 '1.1 Incomplete data processing',
 '[2.2.2 Incorrect Handling of Special Characters]',
 '[2.4.1 Incorrect Output Message]',
 '[1.2.3 Missing null check]',
 '[2.1 Incorrect data processing]',
 '[1.2 Incomplete input validation]',
 '[2.4 Incorrect output]',
 '[1.4 Incomplete Configuration Processing]',
 '[1.1 Incomplete data processing]',
 '[2.5 Incorrect configuration processing]',
 '[2.1.2 Incorrect initialization]',
 '[4 Perfective maintenance]',
 '[2.7 Performance]',
 '[1.4 Incomplete configuration processing]',
 '2.2 Incorrect input validation',
 '[2.1.2 Incorrect Initialization]',
 '[3.3.1 Missing Initialization]',
 '[1.2 Missing Input Validation]',
 '[1.5 Incomplete Output Message]',
 '[1.2.1 Missing Type Check]',
 '4 Perfective maintenance',
 '2.7 Performance',
 '2.2.2 Incorrect handling of special characters',
 '1.2.5 Missing handling of special characters',
 '2.6 Incorrect handling of regex expressions',
 '1 Incomplete feature implementation',
 '2 Incorrect feature implementation',
 '1.3 Error handling',
 '1.2.3 Missing null check',
 '4 Perfective Maintenance']

In [5]:
df['issue_category'] = df['issue_category'].str.strip().str.strip('[]')

In [6]:
print(df['image_category_1'].unique().tolist())
[
    'Web Interface (UI/UX Element), Code Snippet Screenshot',
    'Code Snippet Screenshot, Error Message',
    'Map/Geospatial Visualization, Error Message',
    'Code Snippet Screenshot, Map/Geospatial Visualization',
    'Code Snippet Screenshot, Data Visualization',
    'Map/Geospatial Visualization, Web Interface (UI/UX Element)',
    'Code Snippet Screenshot, Diagram',
    'Diagram, Error Message',
    'Diagram, Web Interface (UI/UX Element), Error Message',
    'Diagram, Web Interface (UI/UX Element)',
    'Code Snippet Screenshot, Web Interface (UI/UX Element)',
    'Code Snippet Screenshot, Miscellaneous',
    'Error Message, Web Interface (UI/UX Element)',
    'Web Interface (UI/UX Element), Diagram',
    'Web Interface (UI/UX Element), Error Message',
    'Error Message, Diagram',
    'Code Snippet Screenshot, Map/Geospatial Visualization, Web Interface (UI/UX Element)',
    'Miscellaneous, Web Interface (UI/UX Element)',
    'Diagram, Web Interface (UI/UX Element), Code Snippet Screenshot, Error Message',
    'Diagram, Web Interface (UI/UX Element), Code Snippet Screenshot',
]

['Diagram', 'Code Snippet Screenshot', 'Web Interface (UI/UX Element)', 'Web Interface (UI/UX Element), Code Snippet Screenshot', 'Error Message', 'Miscellaneous', 'Data Visualization', 'Code Snippet Screenshot, Error Message', 'Map/Geospatial Visualization', 'Map/Geospatial Visualization, Error Message', 'Artwork / Photography', 'Code Snippet Screenshot, Map/Geospatial Visualization', 'Code Snippet Screenshot, Data Visualization', 'Map/Geospatial Visualization, Web Interface (UI/UX Element)', 'Code Snippet Screenshot, Diagram', 'Diagram, Error Message', 'Diagram, Web Interface (UI/UX Element), Error Message', 'Diagram, Web Interface (UI/UX Element)', 'Code Snippet Screenshot, Web Interface (UI/UX Element)', 'Code Snippet Screenshot, Miscellaneous', 'Error Message, Web Interface (UI/UX Element)', 'Web Interface (UI/UX Element), Diagram', 'Web Interface (UI/UX Element), Error Message', 'Error Message, Diagram', 'Code Snippet Screenshot, Map/Geospatial Visualization, Web Interface (UI/UX Element)', 'Miscellaneous, Web Interface (UI/UX Element)', 'Diagram, Web Interface (UI/UX Element), Code Snippet Screenshot, Error Message', 'Diagram, Web Interface (UI/UX Element), Code Snippet Screenshot']

['Web Interface (UI/UX Element), Code Snippet Screenshot',
 'Code Snippet Screenshot, Error Message',
 'Map/Geospatial Visualization, Error Message',
 'Code Snippet Screenshot, Map/Geospatial Visualization',
 'Code Snippet Screenshot, Data Visualization',
 'Map/Geospatial Visualization, Web Interface (UI/UX Element)',
 'Code Snippet Screenshot, Diagram',
 'Diagram, Error Message',
 'Diagram, Web Interface (UI/UX Element), Error Message',
 'Diagram, Web Interface (UI/UX Element)',
 'Code Snippet Screenshot, Web Interface (UI/UX Element)',
 'Code Snippet Screenshot, Miscellaneous',
 'Error Message, Web Interface (UI/UX Element)',
 'Web Interface (UI/UX Element), Diagram',
 'Web Interface (UI/UX Element), Error Message',
 'Error Message, Diagram',
 'Code Snippet Screenshot, Map/Geospatial Visualization, Web Interface (UI/UX Element)',
 'Miscellaneous, Web Interface (UI/UX Element)',
 'Diagram, Web Interface (UI/UX Element), Code Snippet Screenshot, Error Message',
 'Diagram, Web Interface (UI/UX Element), Code Snippet Screenshot']

In [7]:
df['image_category_1'] = df['image_category_1'].str.split(', ')
df = df.explode('image_category_1')

In [8]:
print(df['image_category_2'].unique().tolist())
[
    'Dialog Box, Desired Output',
    'Code, Program Input',
    'Code, Run Time Error',
    'Steps and Processes, Algorithm/Concept Description',
    'Code, Program Output',
    'Code, Program Input, Desired Output',
    None,
    'Desired Output, Program Output',
    'Program Output, Desired Output',
    'Code, Program Input, Program Output',
    'Steps and Processes, Program Output',
    'Program Output, Run Time Error',
    'Program Output, Steps and Processes',
    'Code, Program Output, Menus and Preference',
    'Algorithm/Concept Description, Dialog Box',
    'Run Time Error, Algorithm/Concept Description',
    'Algorithm/Concept Description, Program Output',
    'Algorithm/Concept Description, Menus and Preference',
    'Algorithm/Concept Description, Run Time Error',
    'Steps and Processes, Code, Desired Output',
    'Code, Desired Output',
    'Code, Menus and Preference, Desired Output',
    'Program Input, Code',
    'Code, Menus and Preference, Program Output',
    'Code, Steps and Processes',
    'Code, Desired Output, Program Output',
    'Run Time Error, Program Output',
    'Program Output, Menus and Preference',
    'Run Time Error, Steps and Processes, Menus and Preference, Program Output',
    'Menus and Preference, Program Output, Steps and Processes',
    'Menus and Preference, Program Output, Steps and Processes, Run Time Error',
]

['Program Output', 'Steps and Processes', 'Run Time Error', 'Algorithm/Concept Description', 'Program Output, Code', 'Desired Output', 'Code', 'Dialog Box', 'Menus and Preference', 'Dialog Box, Desired Output', 'Code, Program Input', 'Code, Run Time Error', 'Steps and Processes, Algorithm/Concept Description', 'Code, Program Output', 'Code, Program Input, Desired Output', nan, 'Desired Output, Program Output', 'Program Input', 'Program Output, Desired Output', 'Code, Program Input, Program Output', 'Steps and Processes, Program Output', 'Program Output, Run Time Error', 'Program Output, Steps and Processes', 'Code, Program Output, Menus and Preference', 'Algorithm/Concept Description, Dialog Box', 'Run Time Error, Algorithm/Concept Description', 'Algorithm/Concept Description, Program Output', 'Algorithm/Concept Description, Menus and Preference', 'Algorithm/Concept Description, Run Time Error', 'Steps and Processes, Code, Desired Output', 'Code, Desired Output', 'Code, Menus and Preference, Desired Output', 'Program Input, Code', 'CPU/GPU Performance', 'Code, Menus and Preference, Program Output', 'Code, Steps and Processes', 'Code, Desired Output, Program Output', 'Run Time Error, Program Output', 'Program Output, Menus and Preference', 'Run Time Error, Steps and Processes, Menus and Preference, Program Output', 'Menus and Preference, Program Output, Steps and Processes', 'Menus and Preference, Program Output, Steps and Processes, Run Time Error']

['Dialog Box, Desired Output',
 'Code, Program Input',
 'Code, Run Time Error',
 'Steps and Processes, Algorithm/Concept Description',
 'Code, Program Output',
 'Code, Program Input, Desired Output',
 None,
 'Desired Output, Program Output',
 'Program Output, Desired Output',
 'Code, Program Input, Program Output',
 'Steps and Processes, Program Output',
 'Program Output, Run Time Error',
 'Program Output, Steps and Processes',
 'Code, Program Output, Menus and Preference',
 'Algorithm/Concept Description, Dialog Box',
 'Run Time Error, Algorithm/Concept Description',
 'Algorithm/Concept Description, Program Output',
 'Algorithm/Concept Description, Menus and Preference',
 'Algorithm/Concept Description, Run Time Error',
 'Steps and Processes, Code, Desired Output',
 'Code, Desired Output',
 'Code, Menus and Preference, Desired Output',
 'Program Input, Code',
 'Code, Menus and Preference, Program Output',
 'Code, Steps and Processes',
 'Code, Desired Output, Program Output',
 'Run Time Error, Program Output',
 'Program Output, Menus and Preference',
 'Run Time Error, Steps and Processes, Menus and Preference, Program Output',
 'Menus and Preference, Program Output, Steps and Processes',
 'Menus and Preference, Program Output, Steps and Processes, Run Time Error']

In [9]:
df['image_category_2'] = df['image_category_2'].str.split(', ')
df = df.explode('image_category_2')

In [10]:
def parse_list(val):
    if pd.isna(val):
        return val
    val = val.strip()
    try:
        result = ast.literal_eval(val)
        return result if isinstance(result, list) else [result]
    except (ValueError, SyntaxError):
        # Handles [https://...] style (unquoted)
        if val.startswith("[") and val.endswith("]"):
            return [u.strip() for u in val[1:-1].split(",")]
        return [val]

df['image_assets'] = df['image_assets'].apply(parse_list)
df = df.explode('image_assets')

In [11]:
df.head()

,instance_id,issue_link,problem_statement,issue_category,image_assets,image_category_1,image_category_2,name
0,bpmn-io__bpmn-js-2024,https://github.com/bpmn-io/bpmn-js/issues/57,Correctly render pool / lane labels in vertica...,1.1 Incomplete Data Processing,https://cloud.githubusercontent.com/assets/586...,Diagram,Program Output,daniel
0,bpmn-io__bpmn-js-2024,https://github.com/bpmn-io/bpmn-js/issues/57,Correctly render pool / lane labels in vertica...,1.1 Incomplete Data Processing,https://github.com/bpmn-io/bpmn-miwg-test-suit...,Diagram,Program Output,daniel
1,bpmn-io__bpmn-js-1200,https://github.com/bpmn-io/bpmn-js/issues/1199,"""Timer Intermediate Catch Event"" removes ""cond...",2.1 Incorrect Data Processing,https://user-images.githubusercontent.com/8074...,Code Snippet Screenshot,Steps and Processes,daniel
2,bpmn-io__bpmn-js-1610,https://github.com/bpmn-io/bpmn-js/issues/1609,Direct editing in sub-process plane stays open...,1.3 Error Handling,https://user-images.githubusercontent.com/5860...,Diagram,Program Output,daniel
3,bpmn-io__bpmn-js-1578,https://github.com/bpmn-io/bpmn-js/issues/1555,Error when copy Pool\n__Describe the Bug__\n\n...,2.1 Incorrect Data Processing,https://user-images.githubusercontent.com/1523...,Web Interface (UI/UX Element),Run Time Error,daniel

In [ ]:
df_melted = df.melt(
    id_vars=[
        'name',
        'instance_id',
        'issue_link',
        'problem_statement',
        'image_assets',
    ],
    var_name='key',
    value_name='value',
)
df_melted.head()
df_melted.to_csv('events.csv', index=False)

,name,instance_id,issue_link,problem_statement,image_assets,key,value
0,daniel,bpmn-io__bpmn-js-2024,https://github.com/bpmn-io/bpmn-js/issues/57,Correctly render pool / lane labels in vertica...,https://cloud.githubusercontent.com/assets/586...,issue_category,1.1 Incomplete Data Processing
1,daniel,bpmn-io__bpmn-js-2024,https://github.com/bpmn-io/bpmn-js/issues/57,Correctly render pool / lane labels in vertica...,https://github.com/bpmn-io/bpmn-miwg-test-suit...,issue_category,1.1 Incomplete Data Processing
2,daniel,bpmn-io__bpmn-js-1200,https://github.com/bpmn-io/bpmn-js/issues/1199,"""Timer Intermediate Catch Event"" removes ""cond...",https://user-images.githubusercontent.com/8074...,issue_category,2.1 Incorrect Data Processing
3,daniel,bpmn-io__bpmn-js-1610,https://github.com/bpmn-io/bpmn-js/issues/1609,Direct editing in sub-process plane stays open...,https://user-images.githubusercontent.com/5860...,issue_category,1.3 Error Handling
4,daniel,bpmn-io__bpmn-js-1578,https://github.com/bpmn-io/bpmn-js/issues/1555,Error when copy Pool\n__Describe the Bug__\n\n...,https://user-images.githubusercontent.com/1523...,issue_category,2.1 Incorrect Data Processing

In [14]:
df.dtypes

instance_id          object
issue_link           object
problem_statement    object
issue_category       object
image_assets         object
image_category_1     object
image_category_2     object
name                 object
dtype: object

In [15]:
# with sqlite3.connect("annotations.db") as conn:
#     df.to_sql("annotations", conn, if_exists="replace", index=False)

In [16]:
# with sqlite3.connect("annotations.db") as conn:
#     df = pd.read_sql("SELECT * FROM annotations LIMIT 10", conn)
# df.head()